# Productivity Stats
# Tracks and visualizes your coding productivity metrics

name: Productivity Stats

on:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Generate Productivity Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
